PrivateTraining/Areas/PrivateTrain/Controllers/ServiceLocationController.cs
using PrivateTraining.BussinessLayer.Generic;
using PrivateTraining.DataLayer.Context;
using PrivateTraining.ServiceLayer.Interface.PrivateTraining;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PrivateTraining.DomainClasses.Entities;
using PrivateTraining.DomainClasses.Entities.PrivateTraining;
using PrivateTraining.LocationLayer.Interface.PrivateTraining;
using PrivateTraining.ServiceLocationLayer.Interface.PrivateTraining;
using PrivateTraining.DomainClasses.Entities.BaseTable;
using System.Data.Entity;
using PrivateTraining.DomainClasses.EntitiesView;
using Microsoft.AspNet.Identity;
using PrivateTraining.DomainClasses.EntitiesView.PrivateTrainig;
using PrivateTraining.ServiceLayer.BLL;

namespace PrivateTraining.Areas.PrivateTrain.Controllers
{
    public partial class ServiceLocationController : BaseController
    {
        private readonly ILocation _Location;
        private readonly IServiceLocation _ServiceLocation;
        private readonly IUnitOfWork _uow;
        private readonly IServiceProperties _ServiceProperties;
        private IDbSet<State> _State;
        private IDbSet<ServiceWorkUnit> _ServiceWorkUnit;
        private IDbSet<ServiceLocationWorkUnit> _ServiceLocationWorkUnit;
        private readonly IWorkUnit _WorkUnit;
        List<int> services = new List<int>();
        private readonly IService _Service;
        List<int> ListServiceChild = new List<int>();

        public ServiceLocationController(IUnitOfWork uow, ILocation location, IServiceLocation serviceLocation, IServiceProperties serviceProperties, IWorkUnit workUnit, IService Service)
        {
            _uow = uow;
            _Location = location;
            _ServiceLocation = serviceLocation;
            _ServiceProperties = serviceProperties;
            _State = _uow.Set<State>();
            _ServiceWorkUnit = _uow.Set<ServiceWorkUnit>();
            _ServiceLocationWorkUnit = _uow.Set<ServiceLocationWorkUnit>();
            _WorkUnit = workUnit;
            _Service = Service;

        }
        // GET: PrivateTrain/ServiceLocation
        public virtual ActionResult Index()
        {
            return View();
        }


        public virtual ActionResult Location()
        {
            ViewBag.ListServices = _ServiceProperties.GetAllServiceProperties();
            ViewBag.ListStates = _State.ToList();
            return View();
        }

        /// <summary>
        /// افزودن محل
        /// </summary>
        [HttpPost]
        public virtual async Task<JsonResult> AddServiceLocation(DomainClasses.EntitiesView.PrivateTrainig.View_ServiceLocations paramServiceLocation, int checkboxPercentOfShares, int checkboxPriceRegisterServiceProvider, int checkboxPriceWorkUnitService)
        {
            try
            {
                int Status = 0;
                Location templocation = new Location();
                templocation.Name = paramServiceLocation.LocationName;
                templocation.LocationCode = paramServiceLocation.LocationCode;
                templocation.CityId = paramServiceLocation.CityId;
                templocation.PercentOfShares = checkboxPercentOfShares * paramServiceLocation.PercentOfShares;
                templocation.PercentPriceWorkUnitServiceLocation = checkboxPriceWorkUnitService * paramServiceLocation.PercentPriceWorkUnitServiceLocation;
                templocation.PercentPriceRegisterServiceProvider = checkboxPriceRegisterServiceProvider * paramServiceLocation.PercentPriceRegisterServiceProvider;

                await _Location.AddLocation(templocation);
                await _uow.SaveAllChangesAsync();
                var locationId = templocation.Id;

                var AllServices = await _ServiceProperties.GetAllServiceProperties();
                var ListServicePropertieslevel0 = AllServices.ToList().Where(c => c.ParentId == 0 && c.IsEnable == true);
                foreach (var Query in ListServicePropertieslevel0)
                {
                    subservice(AllServices, Query.Id);
                }

                foreach (var item in services)
                {
                    //---------------------- ثبت خصوصیات خدمت برای محل
                    ServiceProperties tempServiceProperties = await _ServiceProperties.GetServiceProperties(item);
                    DomainClasses.Entities.PrivateTraining.View_ServiceLocations tempServiceLocation = new DomainClasses.Entities.PrivateTraining.View_ServiceLocations();
                    tempServiceLocation.ServiceId = tempServiceProperties.Id;
                    tempServiceLocation.ServiceCode = tempServiceProperties.ServiceCode;
                    tempServiceLocation.LocationId = locationId;
                    tempServiceLocation.LocationCode = paramServiceLocation.LocationCode;
                    tempServiceLocation.ServiceLocationCode = tempServiceLocation.LocationCode + "" + tempServiceLocation.ServiceCode;
                    tempServiceLocation.MaxCapacityService = tempServiceProperties.MaxCapacity;
                    tempServiceLocation.MinCapacityService = tempServiceProperties.MinCapacity;
                    tempServiceLocation.PercentCountReservationService = tempServiceProperties.PercentCountReservation;
                    tempServiceLocation.CityId = templocation.CityId;

                    tempServiceLocation.PercentPriceWorkUnitServiceLocation = checkboxPriceWorkUnitService * (paramServiceLocation.PercentPriceWorkUnitServiceLocation);
                    tempServiceLocation.PercentPriceRegisterServiceProvider = checkboxPriceRegisterServiceProvider * (paramServiceLocation.PercentPriceRegisterServiceProvider);
                    //tempServiceLocation.CapacityServiceProvider = tempServiceProperties.CapacityServiceProvider;
                    tempServiceLocation.PercentOfShares = checkboxPercentOfShares * (paramServiceLocation.PercentOfShares) + (tempServiceProperties.PercentOfShares);

                    tempServiceLocation.CalculationPriceRegisterServiceProvider = (tempServiceProperties.PriceRegisterServiceProvider) + ((tempServiceLocation.PercentPriceRegisterServiceProvider / 100) * (tempServiceProperties.PriceRegisterServiceProvider));

                    await _ServiceLocation.AddServiceLocation(tempServiceLocation);
                    Status = await _uow.SaveAllChangesAsync();

                    //---------------------- ثبت قیمت های واحد کار تعریف شده خدمت ؛ برای محل
                    var listServiceWorkUnit = _ServiceWorkUnit.Where(c => c.ServicePropertiesId == tempServiceLocation.ServiceId).ToList();
                    foreach (var item2 in listServiceWorkUnit)
                    {
                        ServiceLocationWorkUnit tempServiceLocationWorkUnit = new ServiceLocationWorkUnit();
                        tempServiceLocationWorkUnit.ServiceLocationId = tempServiceLocation.Id;
                        tempServiceLocationWorkUnit.WorkUnitId = item2.WorkUnitId;
                        tempServiceLocationWorkUnit.PriceWorkUnit = item2.PriceWorkUnit;
                        tempServiceLocationWorkUnit.CalculationPriceServiceLocationWorkUnit = item2.PriceWorkUnit + (tempServiceLocation.PercentPriceWorkUnitServiceLocation / 100) * item2.PriceWorkUnit;
                        _ServiceLocationWorkUnit.Add(tempServiceLocationWorkUnit);
                        Status = await _uow.SaveAllChangesAsync();
                    }

                }

                return Json(new { Result = true, Messages = Status });
            }
            catch (Exception ex)
            {
                return Json(new { Result = false, Messages = "" });
            }

        }

        public void subservice(IEnumerable<ServiceProperties> ServiceProperties, int GId)
        {
            var TempServices = ServiceProperties.Where(c => c.ParentId == GId).ToList();

            if (TempServices.Count() == 0)
            {
                services.Add(GId);
            }

            foreach (var item in TempServices)
            {
                subservice(ServiceProperties, item.Id);
            }

        }

        [HttpPost]
        public virtual async Task<JsonResult> ListLocation()
        {
            try
            {
                datatable datatable = new datatable();
                datatable = datatableclasses.getdatatalbe(Request);

                var list = await _Location.GetAllLocation();
                list = list.Where(c => c.IsEnable == true);

                if (!string.IsNullOrEmpty(datatable.searchValue))
                {
                    // list = list.Where(c => c.Title.Contains(datatable.searchValue));
                }
                datatable.recordsTotal = list.Count();
                list = list.OrderBy(c => c.Id).Skip(datatable.skip).Take(datatable.pageSize);

                // Select Feild
                datatable.data = list.ToList().Select(rec => new string[]
                {
                 "<div class=\"checkbox\" style=\"margin-right:-20px;padding-left:5px;\"><label><input type=\"checkbox\" ng-model=\"checkbox["+rec.Id+"]\" ng-checked=all class=\"case\" value=\""+rec.Id +"\" ><span class=\"text\"></span></lable></div>"
                /*+rec.Id*/,
                rec.LocationCode.ToString(),
                rec.Name,
                rec.Cities.Name,
                rec.Cities.States.Name,
                StatusName(rec.IsEnable,rec.Id),

                }).ToList();

                datatable.draw = datatable.draw;
                datatable.recordsFiltered = datatable.recordsTotal;
                datatable.recordsTotal = datatable.recordsTotal;

                return Json(datatable);
            }
            catch (Exception ex)
            {

                return Json(null);
            }

        }

        public string StatusName(bool IsEnable, int Id)
        {
            string Status = "";
            if (IsEnable)

PrivateTraining/Areas/PrivateTrain/Views/ServiceLocation/GetListServiceLocation.cshtml
@{
    ViewBag.Title = "لیست خدمت - محل ها ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="widget-body">
        <div class="ClassBoxSearch">
            <div class="row PaddingBottom">
                <div class="col-lg-2 text-left">
                    استان
                </div>
                <div class="col-lg-3">
                    <select class="form-control" ng-model="StateId" ng-change="City(0)" name="StateId" required>
                        <option value="0" ng-selected="true">همه</option>

                        @foreach (var item in ViewBag.ListStates)
                        {
                            <option value="@item.Id">@item.Name</option>
                        }
                    </select>
                </div>

                <div class="col-lg-2 text-left">
                    شهر
                </div>
                <div class="col-lg-3">
                    <select class="form-control" ng-model="CityId" ng-change="Location(0)" name="CityId" required>
                        <option value="0" ng-selected="true">همه</option>
                        <option ng-repeat="sub in Cities" value="{{sub.Id}}">{{sub.Name}}</option>
                    </select>
                </div>
            </div>

            <div class="row PaddingBottom" id="locationid">
                <div class="col-lg-2 text-left">
                    محدوده
                </div>
                <div class="col-lg-3 ">
                    <select id="UserLocations" ng-model="LocationId" name="LocationId" style="width:100%"  required>
                        <option value="0" ng-selected="true">همه</option>

                        <option ng-repeat="sub in Locations" value="{{sub.Id}}">{{sub.Name}}</option>
                    </select>
                </div>

                <div class="col-lg-2 text-left">
                    خدمات
                </div>
                <div class="col-lg-3">
                    <select id="UserServices" ng-model="ServiceId" name="ServiceId" style="width:100%" required>
                        <option value="0" ng-selected="true">همه</option>
                        @foreach (var item in ViewBag.Services)
                        {
                            <option value="@item.Id">@item.Title</option>
                        }

                    </select>
                </div>
            </div>
            <div class="row PaddingBottom">
                <div class="col-lg-2 text-left">

                </div>
                <div class="col-lg-4">
                    <a class="btn btn-warning " href="#" ng-click="Realod()"> جستجو</a>
                </div>
            </div>
        </div>
        <br />
        <div ng-controller="MainCtrl as list">
            <table datatable="" dt-options="list.dtOptions" dt-columns="list.dtColumns" dt-instance="list.dtInstance" class="table table-hover table-responsive ng-isolate-scope dataTable table-bordered table-striped"></table>
        </div>


    </div>
</div>

    </div>

@section scripts{

    <script>
        $(".ServiceLocation-getlistservicelocation").addClass("active").parents("li").addClass("open");
        $("#UserServices").select2({});
        $("#UserLocations").select2({});

        app.controller('MainCtrl', function ($scope, $http, $compile, DTOptionsBuilder, DTColumnBuilder, DTInstances) {
            vm = this;
            vm.dtOptions = DTOptionsBuilder.newOptions()
           .withOption('ajax', {
               url: "@Url.Action(MVC.PrivateTrain.ServiceLocation.Actions.ListServiceLocation())",
               type: 'POST',
               data: function (data) {
                   data.StateId = $scope.StateId;
                   data.CityId = $scope.CityId;
                   data.LocationId = $scope.LocationId;
                   data.ServiceId = $scope.ServiceId;
               },
               error: function (xhr, ajaxOptions, thrownError) {
                   NotifyCustom(xhr.responseText, 'danger');
               }
           })
          .withDataProp('data')
     .withOption('processing', true)
     .withOption('serverSide', true)
     .withOption('fnRowCallback', function (nRow, aData, iDisplayIndex, iDisplayIndexFull) { $compile(nRow)($scope) })
     .withPaginationType('full_numbers')
     .withOption('aaSorting', [0, 'desc'])
              .withOption('dom', '<"pull-left"f>ltpr')
     .withDisplayLength(10);

            vm.dtColumns = [
                DTColumnBuilder.newColumn([1]).withTitle('استان'),
                DTColumnBuilder.newColumn([2]).withTitle('شهر'),
                DTColumnBuilder.newColumn([3]).withTitle('نام محل').withOption('name', ''),
                DTColumnBuilder.newColumn([4]).withTitle('نام خدمت').withOption('name', ''),
                DTColumnBuilder.newColumn([5]).withTitle('کد محل').withOption('name', 'LocationCode'),
                DTColumnBuilder.newColumn([6]).withTitle('کد خدمت ').withOption('name', 'ServiceCode'),
                DTColumnBuilder.newColumn([7]).withTitle('کد خدمت محل').withOption('name', 'ServiceLocationCode'),
                DTColumnBuilder.newColumn(null).withTitle('صفحه اختصاصی ').notSortable()
                .renderWith(function (data, type, full, meta) {
                    //return '<button class="btn btn-info" onclick="GetServiceLocationPrivate(' + data[0] + ')">صفحه اختصاصی</button>';
                    return '<a href="/PrivateTrain/ServiceLocation/GetServiceLocationPrivate?Id=' + data[0] + '"  title=\"صفحه اختصاصی\" target=\"_blank\" class="btn btn-magenta shiny btn-circle btn-xs"><span class="typcn typcn-info-large"></span></a>';
                }).withOption("class", "text-center"),

            ];
            DTInstances.getLast().then(function (dtInstance) {
                vm.dtInstance = dtInstance;
            });
            $scope.Realod = function (event, loadedDT) {
                vm.dtInstance.reloadData();
            }

            $scope.City = function (DefaultCityId) {
                $http.post('@Url.Action(MVC.BaseInfo.BaseInfo.Actions.ListCity())', { "StateId": $scope.StateId, "DefaultCityId": DefaultCityId }).success(function (response) {
                    $scope.Cities = response.list;
                    // $scope.Realod();
                });
            }

            $scope.Location = function (DefaultLocationId) {
                $scope.Locations = {};
                $http.post('@Url.Action(MVC.PrivateTrain.ServiceLocation.Actions.ListLocationGetByCityId())', { "CityId": $scope.CityId, "DefaultLocationId": DefaultLocationId }).success(function (response) {
                    if (response.Resualt) {
                        $scope.Locations = response.list;
                        //$("#locationid").show();
                    }
                    else {
                        //$("#locationid").hide();
                    }
                });
            }
            //$scope.GetServiceLocationPrivate = function (Id) {
            //    window.location.href = '/PrivateTrain/ServiceLocation/GetServiceLocationPrivate?Id=' + Id;
            //}
        });

    </script>

}

PrivateTraining/Areas/PrivateTrain/Views/ServiceLocation/GetServiceLocationPrivate.cshtml
@using PrivateTraining.DomainClasses.Entities.PrivateTraining;
@{
    ViewBag.Title = "صفحه اختصاصی خدمت - محل";

}
<style>
    input[type="text"], input[type="password"], select.form-control, .input-group {
        width: 200px;
    }

    label {
        float: right;
        width: 174px;
    }

    .checkbox label {
        width: 120px;
    }
</style>
<div>
    <div class="row">
        <div class="widget-body" style="padding-top:50px;">
            <form name="AddForm" novalidate ng-submit="AddEdit(AddForm.$valid) ">
                <input type="hidden" ng-model="ServiceLocation.Id" />
                <div class="form-group col-md-6">
                    <label>نام خدمت</label>
                    {{ServiceLocation.ServiceName}}
                </div>
                <div class="form-group col-md-6">
                    <label>نام محل</label>
                    {{ServiceLocation.LocationName}}
                </div>
                <div class="form-group col-md-6">
                    <label>کد خدمت</label>
                    @*<input type="text" class="form-control" placeholder="" ng-model="ServiceLocation.ServiceCode" name="ServiceCode" disabled>*@
                    {{ServiceLocation.ServiceCode}}
                </div>
                <div class="form-group col-md-6">
                    <label>کد محل</label>
                    @*<input type="text" class="form-control" placeholder="" ng-model="ServiceLocation.LocationCode" name="LocationCode" disabled>*@
                    {{ServiceLocation.LocationCode}}
                </div>
                <div class="form-group col-md-6">
                    <label>کد خدمت - محل </label>
                    @*<input type="text" class="form-control" placeholder="" ng-model="ServiceLocation.ServiceLocationCode" name="ServiceLocationCode" disabled>*@
                    {{ServiceLocation.ServiceLocationCode}}
                </div>
                <div class="form-group col-md-6">
                    <label>حداکثر ظرفیت خدمتیار</label>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="" ng-model="ServiceLocation.MaxCapacityService" name="MaxCapacityService" required>
                        <span class="input-group-addon">نفر</span>
                    </div>
                    <span style="color:red" ng-show="AddForm.$submitted && AddForm.MaxCapacityService.$invalid">
                        <span ng-show="AddForm.MaxCapacityService.$error.required ">لطفا حداکثر ظرفیت خدمت را وارد نمایید</span>
                    </span>
                </div>
                <div class="form-group col-md-6">
                    <label>حداقل ظرفیت خدمتیار</label>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="" ng-model="ServiceLocation.MinCapacityService" name="MinCapacityService" required>
                        <span class="input-group-addon">نفر</span>
                    </div>
                    <span style="color:red" ng-show="AddForm.$submitted && AddForm.MinCapacityService.$invalid">
                        <span ng-show="AddForm.MinCapacityService.$error.required ">لطفا حداقل ظرفیت خدمت را وارد نمایید</span>
                    </span>
                </div>
                <div class="form-group col-md-6">
                    <label>درصد تعداد رزرو</label>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="" ng-model="ServiceLocation.PercentCountReservationService" name="PercentCountReservationService" required>
                        <span class="input-group-addon">%</span>
                    </div>
                    <span style="color:red" ng-show="AddForm.$submitted && AddForm.PercentCountReservationService.$invalid">
                        <span ng-show="AddForm.PercentCountReservationService.$error.required ">لطفا درصد تعداد رزرو را وارد نمایید</span>
                    </span>
                </div>

                @*<div class="form-group col-md-6">
                    <label>ظرفیت خدمتیار</label>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="" ng-model="ServiceLocation.CapacityServiceProvider" name="CapacityServiceProvider" required>
                        <span class="input-group-addon">نفر</span>
                    </div>
                    <span style="color:red" ng-show="AddForm.$submitted && AddForm.CapacityServiceProvider.$invalid">
                        <span ng-show="AddForm.CapacityServiceProvider.$error.required ">لطفا ظرفیت خدمتیار را وارد نمایید</span>
                    </span>
                </div>*@
                <div class="form-group col-md-6">
                    <label>درصد حق السهم شرکت</label>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="" ng-model="ServiceLocation.PercentOfShares" name="PercentOfShares" required>
                        <span class="input-group-addon">%</span>
                    </div>
                    <span style="color:red" ng-show="AddForm.$submitted && AddForm.PercentOfShares.$invalid">
                        <span ng-show="AddForm.PercentOfShares.$error.required ">لطفا حق السهم شرکت را وارد نمایید</span>
                    </span>
                </div>
                <div class="form-group col-md-6">
                    <label> قیمت ثبت نام خدمتیار </label>
                    <div class="input-group" style="float:right">
                        <input type="text" class="form-control" placeholder="" ng-model="ServiceLocation.CalculationPriceRegisterServiceProvider" name="CalculationPriceRegisterServiceProvider" required>
                        <span class="input-group-addon">تومان</span>
                    </div>
                    <span style="color:red" ng-show="AddForm.$submitted && AddForm.CalculationPriceRegisterServiceProvider.$invalid">
                        <span ng-show="AddForm.CalculationPriceRegisterServiceProvider.$error.required ">لطفا  قیمت ثبت نام خدمتیار را وارد نمایید</span>
                    </span>
                </div>
                <div class="form-group col-md-12">
                    <label>لیست واحد کار</label>
                    <div style="">
                        <div ng-repeat="x in ListWorkUnits" style="clear:both">
                            <div class="checkbox" style="float:right;padding-right:10px;">
                                <label>
                                    <input type="checkbox" class="form-control serviceId" ng-model="x.selected" ng-value="{{x.WorkUnitId}}" name="WorkUnits">
                                    <span class="text">{{x.WorkUnitTitle}}</span>
                                </label>
                            </div>
                            <div style="float:right;padding-right:10px;position:relative;top:11px">
                                <span style="padding-left:15px;float:right">قیمت هر واحد کار</span>
                                <div class="input-group" style="width:130px;float:right">
                                    <input type="text" class="form-control " ng-model="x.PriceWorkUnit" name="PriceWorkUnitServiceId" style="width:80px;display:inline-block;padding:3px 6px;" id="PriceWorkUnitServiceId">
                                    <span class="input-group-addon">تومان</span>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                @*<div class="form-group col-md-6">
                        <label>درصد حق السهم شرکت</label>
                        <input type="text" class="form-control" placeholder="" ng-model="ServiceLocation.PercentOfShares" name="PercentOfShares" required>
                        <span style="color:red" ng-show="AddForm.$submitted && AddForm.PercentOfShares.$invalid">
                            <span ng-show="AddForm.PercentOfShares.$error.required ">لطفا حق السهم شرکت را وارد نمایید</span>
                        </span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>درصد قیمت ثبت نام خدمتیار </label>
                        <input type="text" class="form-control" placeholder="" ng-model="ServiceLocation.PriceRegisterServiceProvider" name="PriceRegisterServiceProvider" required>
                        <span style="color:red" ng-show="AddForm.$submitted && AddForm.PriceRegisterServiceProvider.$invalid">
                            <span ng-show="AddForm.PriceRegisterServiceProvider.$error.required ">لطفا درصد قیمت ثبت نام خدمتیار را وارد نمایید</span>
                        </span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>درصد قیمت هر واحد کار</label>
                        <input type="text" class="form-control" placeholder="" ng-model="ServiceLocation.PriceWorkUnitService" name="PriceWorkUnitService" required>
                        <span style="color:red" ng-show="AddForm.$submitted && AddForm.PriceWorkUnitService.$invalid">
                            <span ng-show="AddForm.PriceWorkUnitService.$error.required ">لطفا درصد قیمت هر واحد کار را وارد نمایید</span>
                        </span>
                    </div>*@
              
                
                <div class="" style="clear:both;padding-top:20px;text-align:left">
                    <button data-bb-handler="confirm" type="submit" class="btn btn-success" ng-click="EditServiceLocation() ">ذخیره</button>
                    <a  class="btn btn-magenta" ng-href="@Url.Action("GetListServiceLocation", "ServiceLocation")">لیست خدمت محل ها</a>
                </div>
            </form>

        </div>
    </div>



</div>

@section Scripts
{
    <script>
        $("select[name=services]").select2();
        angular.module('App').controller('MainCtrl', function ($rootScope, $scope, $http, $compile) {
            $scope.ServiceLocation = {};
            $scope.Listservices={};
            $scope.ListWorkUnits={};
            angular.element(document).ready(function () {
                $http.post('@Url.Action(MVC.PrivateTrain.ServiceLocation.Actions.LoadEditServiceLocationPrivate())', {"Id":@ViewBag.Id}).success(function (response) {
                    $scope.ServiceLocation = response.tempServiceLocation;
                    $scope.Listservices=response.listServicePeroperties;
                    $scope.ListWorkUnits=response.listWorkUnits;

                });
            });



            $scope.EditServiceLocation=function(){
                $scope.ArrayWorkunit = [];
                $scope.ArrayPrice = [];
                $scope.PriceWorkUnit={};
                angular.forEach($scope.ListWorkUnits, function (x) {
                    if (!!x.selected) {
                        $scope.ArrayWorkunit.push(x.WorkUnitId);
                        $scope.ArrayPrice.push(x.PriceWorkUnit);
                    }
                })


                $http.post('@Url.Action(MVC.PrivateTrain.ServiceLocation.Actions.EditServiceLocationPrivate())', {"paramServiceLocation":$scope.ServiceLocation,"Workunits":$scope.ArrayWorkunit,"PriceWorkUnits":$scope.ArrayPrice}).success(function (response) {
                    if(response.Result){
                        NotifyCustom("ویرایش با موفقیت انجام شد", 'success');
                    }
                    else{
                        NotifyCustom('ویرایش انجام نشد', 'danger');
                    }
                });
            }


        });
    </script>
}

PrivateTraining/Areas/PrivateTrain/Views/ServiceLocation/_Delete.cshtml
<div class="modal" id="DeleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="bootbox-close-button close" data-dismiss="modal" aria-hidden="True">x</button>
                <h4 class="modal-title">حذف واحد کار</h4>
            </div>
            <div class="modal-body">
                آیا مایل به حذف می باشید؟
            </div>
            <div class="modal-footer">
                <button data-bb-handler="confirm" type="button" class="btn btn-danger" ng-click="DeleteLocation()">حذف</button>
                <button data-bb-handler="cancel" type="button" class="btn btn-default" ng-click="Cancel()">انصراف</button>
            </div>
        </div>
    </div>
</div>